import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Le blog de Lyon Palme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="bg-purple-50 text-purple-900 py-4 px-6">
          <h1 className="text-xl font-semibold">B2LP - le blog de Lyon Palme</h1>
        </header>

        {/* Contenu principal */}
        {children}

        {/* Footer */}
        <footer className="bg-slate-100 text-purple-900 py-4 px-6 mt-auto">
          <p className="text-sm text-center">
            Développé avec ❤️ par les SIO2 - © 2026
          </p>
        </footer>
      </body>
    </html>
  );
}
